source 'http://rubygems.org'
gem 'cucumber', '~> 3.1', '>= 3.1.2'
gem 'watir-webdriver', '0.7.0'
gem 'watir'
gem 'selenium-webdriver'
gem 'headless', '0.2.2'
gem 'titleize', '1.2.1'
gem 'gherkin', '~> 5.1.0'
gem 'syntax'
gem 'rake', '~> 13.0', '>= 13.0.1'
gem 'rake-compiler', '~> 1.1'
gem 'rake-compiler-dock', '~> 1.0', '>= 1.0.1'
gem 'rspec', '~> 3.9'
gem 'rubygems-tasks', '~> 0.2.5'
ruby "2.3.7"
